export const fakeDataHotel = 
[
    {
        id: 1,
        name: 'Light bright airy stylish apt & safe peaceful stay',
        guests: 5,
        bedRooms: 4, 
        beds: 3, 
        baths: 3,
        rating: 4.9,
        ratingPeople: 20,
        pricePerNight: 41,
        priceTotal: 100,
        img: 'https://i.ibb.co/ZB1KPGs/Rectangle26.png'
    },
    {
        id: 2,
        name: 'Apartment in Lost Panorama',
        guests: 2,
        bedRooms: 1, 
        beds: 1, 
        baths: 2,
        rating: 4.8,
        ratingPeople: 15,
        pricePerNight: 25,
        priceTotal: 150,
        img: 'https://i.ibb.co/ByQDw98/Rectangle-27.png'
    },
    {
        id: 3,
        name: 'AR Lounge & Pool (r&r + b&b)',
        guests: 4,
        bedRooms: 2, 
        beds: 4, 
        baths: 4,
        rating: 4.9,
        ratingPeople: 27,
        pricePerNight: 75,
        priceTotal: 170,
        img: 'https://i.ibb.co/PMc1v01/Rectangle28.png'
    },
    {
        id: 4,
        name: '',
        guests: 3,
        bedRooms: 4, 
        beds: 2, 
        baths: 4,
        rating: 3.9,
        ratingPeople: 50,
        pricePerNight: 15,
        priceTotal: 85,
        img: ''
    },
    {
        id: 5,
        name: '',
        guests: 10,
        bedRooms: 4, 
        beds: 6, 
        baths: 4,
        rating: 4.5,
        ratingPeople: 150,
        pricePerNight: 89,
        priceTotal: 78,
        img: ''
    },
    {
        id: 6,
        name: '',
        guests: 8,
        bedRooms: 5, 
        beds: 6, 
        baths: 7,
        rating: 4.9,
        ratingPeople: 37,
        pricePerNight: 80,
        priceTotal: 180,
        img: ''
    },
    {
        id: 7,
        name: '',
        guests: 5,
        bedRooms: 4, 
        beds: 3, 
        baths: 3,
        rating: 4.9,
        ratingPeople: 20,
        pricePerNight: 41,
        priceTotal: 100,
        img: ''
    },
    {
        id: 8,
        name: '',
        guests: 2,
        bedRooms: 1, 
        beds: 1, 
        baths: 2,
        rating: 4.8,
        ratingPeople: 15,
        pricePerNight: 25,
        priceTotal: 150,
        img: ''
    },
    {
        id: 9,
        name: '',
        guests: 4,
        bedRooms: 2, 
        beds: 4, 
        baths: 4,
        rating: 4.9,
        ratingPeople: 27,
        pricePerNight: 75,
        priceTotal: 170,
        img: ''
    }
]